rule "BREAST CANCER Screen Survey"
  dialect "mvel"
  enabled true
  when
    FhirPatient(ageInYears >= 40)
    FhirPatient(ageInYears < 50)
    Patient(gender == "female")
  then
    drools.setFocus("BREAST_CANCER_SCREENING")
end

rule "BREAST CANCER Rule 1 - No Family History BREAST CANCER "
  dialect "mvel"
  enabled true
  agenda-group "BREAST_CANCER_SCREENING"
  salience 500

  when
    $patient : Patient()
      FhirPatient(ageInYears >= 40)
      FhirPatient(ageInYears < 50)

      // Patient does NOT have First Degree Relation (FDR) that had CRC before age 60
      (
      List(size == 0) from collect(FamilyMemberHistory() from getFamilyMemberHistories( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|174.9", true)) and
      List(size == 0) from collect(FamilyMemberHistory() from getFamilyMemberHistories( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|175.9", true)) and
      List(size == 0) from collect(FamilyMemberHistory() from getFamilyMemberHistories( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|V10.3", true)) and
      List(size == 0) from collect(FamilyMemberHistory() from getFamilyMemberHistories( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|233.0", true)) and
      List(size == 0) from collect(FamilyMemberHistory() from getFamilyMemberHistories( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|V84.01", true)) and
      List(size == 0) from collect(FamilyMemberHistory() from getFamilyMemberHistories( patientRegistrations, "http://hl7.org/fhir/sid/icd-10|Z85.3", true)) and
      List(size == 0) from collect(FamilyMemberHistory() from getFamilyMemberHistories( patientRegistrations, "http://hl7.org/fhir/sid/icd-10|C50", true)) and
      List(size == 0) from collect(FamilyMemberHistory() from getFamilyMemberHistories( patientRegistrations, "http://snomed.info/sct|254837009", true))
      )

      // Patient does NOT have history of breast cancer or genomic markers making them higher risk
      (
      List(size == 0) from collect(FhirResultObject() from getResult( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|174.9", ResultTypeEnum.CONDITION, "ANY")) and
      List(size == 0) from collect(FhirResultObject() from getResult( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|175.9", ResultTypeEnum.CONDITION, "ANY")) and
      List(size == 0) from collect(FhirResultObject() from getResult( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|V10.3", ResultTypeEnum.CONDITION, "ANY")) and
      List(size == 0) from collect(FhirResultObject() from getResult( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|233.0", ResultTypeEnum.CONDITION, "ANY")) and
      List(size == 0) from collect(FhirResultObject() from getResult( patientRegistrations, "http://hl7.org/fhir/sid/icd-9-cm|V84.01", ResultTypeEnum.CONDITION, "ANY")) and
      List(size == 0) from collect(FhirResultObject() from getResult( patientRegistrations, "http://hl7.org/fhir/sid/icd-10|Z85.3", ResultTypeEnum.CONDITION, "ANY")) and
      List(size == 0) from collect(FhirResultObject() from getResult( patientRegistrations, "http://hl7.org/fhir/sid/icd-10|C50", ResultTypeEnum.CONDITION, "ANY")) and
      List(size == 0) from collect(FhirResultObject() from getResult( patientRegistrations, "http://snomed.info/sct|254837009", ResultTypeEnum.CONDITION, "ANY"))
      )


      // No History of past FIT, FIT-DNA, or Colonoscopy
      ArrayList(size == 0) from collect(FhirResultObject() from getResult(patientRegistrations, buildKeyFromConcept( "http://www.ama-assn.org/go/cpt", "76090"), getWithinLastDayJoda(730), getWithinLastDayJoda(0), ResultTypeEnum.PROCEDURE, "ANY"))
      ArrayList(size == 0) from collect(FhirResultObject() from getResult(patientRegistrations, buildKeyFromConcept( "http://www.ama-assn.org/go/cpt", "76091"), getWithinLastDayJoda(730), getWithinLastDayJoda(0), ResultTypeEnum.PROCEDURE, "ANY"))
      ArrayList(size == 0) from collect(FhirResultObject() from getResult(patientRegistrations, buildKeyFromConcept( "http://www.ama-assn.org/go/cpt", "76092"), getWithinLastDayJoda(730), getWithinLastDayJoda(0), ResultTypeEnum.PROCEDURE, "ANY"))

  then

    // cacheAssert(drools, "noFDRHistoryCRC")

    QuestionnaireQuestionResultBuilder builder = new QuestionnaireQuestionResultBuilder();
    Group group =  builder
      .startGroup("BC-1", "http://regenstrief.org/cds/", "PreventionSurvey", "Breast Cancer", "name2", true)
        .addQuestion("BC-1.1", "http://regenstrief.org/cds/", "BC_HISTORY", "Have you ever been diagnosed with breast cancer?", AnswerFormatEnum.CHOICE, new ResourceReferenceDt("#yesno"))
        .addQuestion("BC-1.2", "http://regenstrief.org/cds/", "BC_FDR_HISTORY", "Do you have a parent, sibling, or child who was diagnosed with breast cancer?", AnswerFormatEnum.CHOICE, new ResourceReferenceDt("#yesno"))
        .addQuestion("BC-1.3", "http://regenstrief.org/cds/", "BC_GENOMIC_MARKERS", "Do you have either of the genes for breast cancer? (BRCA1 or BRCA2)", AnswerFormatEnum.CHOICE, new ResourceReferenceDt("#yesno"))
        .addQuestion("BC-1.4", "http://regenstrief.org/cds/", "BC_RADIATION", "Have you been treated with radiation to either breast?", AnswerFormatEnum.CHOICE, new ResourceReferenceDt("#yesno"))
        .addQuestion("BC-1.5", "http://regenstrief.org/cds/", "BC_LESIONS", "Have you had a biopsy on either breast?", AnswerFormatEnum.CHOICE, new ResourceReferenceDt("#yesno"))
      .endGroup()
    .getGroup();

    DroolsRuleResponse resp1 = new DroolsRuleResponse("CRC CDS-HOOKS card\n\nPatient Name:  " + $patient.getNameFirstRep().getNameAsSingleString() + " \n\nPatient Age:  " +getAgeInYears($patient.getBirthDate()) + " ","CDS", "SURVEY_QUESTION");
    resp1.putValue("GROUP", group);
    insert(resp1);

end